// <auto-generated />
using System;
using MQTroco.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MQTroco.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211024193713_CaixaMoeda")]
    partial class CaixaMoeda
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("MQTroco.Models.CaixaModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Caixas");
                });

            modelBuilder.Entity("MQTroco.Models.CaixaMoedaModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaixaModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoedaModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdMoeda")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CaixaMoedas");
                });

            modelBuilder.Entity("MQTroco.Models.MoedaModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(1,2)");

                    b.HasKey("Id");

                    b.ToTable("Moedas");
                });
#pragma warning restore 612, 618
        }
    }
}
